Controllers/RoomTypeController.cs
using HotelApp.Database;
using HotelApp.Repository;
using HotelApp.ViewModel;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace HotelApp.Controllers
{
    public class RoomTypeController : Controller
    {
        private readonly HotelAppContext _context;
        private readonly RoomTypeRepository _roomTypeRepository;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public RoomTypeController(HotelAppContext context,
            RoomTypeRepository roomTypeRepository,
            IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _roomTypeRepository = roomTypeRepository;
            _webHostEnvironment = webHostEnvironment;
        }

        public async Task<IActionResult> Index()
        {
            var data = await _roomTypeRepository.GetAllRoomTypes();
            return View(data);
        }

        public async Task<IActionResult> AddOrEdit(RoomTypeModel model, int id = 0)
        {
            RoomTypeModel roomType = new RoomTypeModel();
            if (id != 0)
            {
                roomType = await _roomTypeRepository.GetRoomTypeById(id);
            }
            ViewBag.feature = new SelectList(await _context.Feature.ToListAsync(), "FeatureID", "FeatureName");
            return View(roomType);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrEdit(int id, RoomTypeModel model)
        {
            if (ModelState.IsValid)
            {
                await _roomTypeRepository.AddOrEditRoomType(model);
                return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this, "_RoomTypePartial", _context.RoomType.ToList()) });
            }
            ViewBag.feature = new SelectList(await _context.Feature.ToListAsync(), "FeatureID", "FeatureName");
            return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "AddOrEdit", model) });
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var roomType = await _context.RoomType.FindAsync(id);
            _context.RoomType.Remove(roomType);
            await _context.SaveChangesAsync();
            return Json(new { html = Helper.RenderRazorViewToString(this, "_RoomTypePartial", _context.RoomType.ToList()) });
        }

        //private async Task<List<RoomType>> GetData()
        //{
        //    var roomTypes = new List<RoomType>();
        //    var allRoomType = await _context.RoomType.ToListAsync();
        //    var allData = await(from x in _context.RoomType
        //                        join y in _context.Feature
        //                        on x.FeatureID equals y.FeatureID
        //                        select new
        //                        {
        //                            x.RoomTypeID,
        //                            x.Name,
        //                            x.BasePrice,
        //                            x.MaxPersonAccept,
        //                            y.FeatureName,
        //                            x.Description
        //                        }).ToListAsync();
        //    if (allData?.Any() == true)
        //    {
        //        foreach (var roomType in allData)
        //        {
        //            roomTypes.Add(new RoomType()
        //            {
        //                RoomTypeID = roomType.RoomTypeID,
        //                Name = roomType.Name,
        //                BasePrice = roomType.BasePrice,
        //                MaxPersonAccept = roomType.MaxPersonAccept,
        //                FeatureName = roomType.FeatureName,
        //                Description = roomType.Description
        //            });
        //        }
        //    }
        //    return roomTypes;
        //}
    }
}

Views/RoomType/AddOrEdit.cshtml
@model HotelApp.ViewModel.RoomTypeModel

@{
    ViewData["Title"] = "AddOrEdit";
    Layout = null;
}

<div class="row">
    <div class="col-md-12">
        <form method="post" asp-action="AddOrEdit" asp-route-id="@Model.RoomTypeID" enctype="multipart/form-data" onsubmit="return jQueryAjaxPost(this);" autocomplete="off">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="RoomTypeID" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BasePrice" class="control-label"></label>
                <input asp-for="BasePrice" class="form-control" />
                <span asp-validation-for="BasePrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaxPersonAccept" class="control-label"></label>
                <input asp-for="MaxPersonAccept" class="form-control" />
                <span asp-validation-for="MaxPersonAccept" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FeatureID" class="control-label" ></label>
                <select asp-for="FeatureID" asp-items="ViewBag.feature" class="form-control">
                    <option value="">-- Select Feature --</option>
                </select>
                <span asp-validation-for="FeatureID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="SUBMIT" class="btn btn-primary btn-block" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/RoomType/Index.cshtml
@model IEnumerable<HotelApp.ViewModel.RoomTypeModel>

@{
    ViewData["Title"] = "Index";
}

<h1 class="text-center">Room Type</h1>

<div id="view-all">
    @await Html.PartialAsync("_RoomTypePartial", Model)
</div>

Views/RoomType/_RoomTypePartial.cshtml
@model IEnumerable<HotelApp.ViewModel.RoomTypeModel>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.RoomTypeID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BasePrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MaxPersonAccept)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Feature)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                <a onclick="showInPopup('@Url.Action("AddOrEdit", "RoomType", null, Context.Request.Scheme)', 'New RoomType')"
                   class="btn btn-success text-white">
                    Create New
                </a>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.RoomTypeID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BasePrice)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MaxPersonAccept)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Feature)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    <a onclick="showInPopup('@Url.Action("AddOrEdit", "RoomType", new { id = item.RoomTypeID }, Context.Request.Scheme)', 'Update RoomType')" class="btn btn-info text-white">
                        Edit
                    </a>
                    <form asp-action="Delete" asp-route-id="@item.RoomTypeID" onsubmit="return jQueryAjaxDelete(this);" class="d-inline">
                        <input type="submit" value="DELETE" class="btn btn-danger" />
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>