Controllers/HotelController.cs
using HotelApp.Database;
using HotelApp.Repository;
using HotelApp.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HotelApp.Controllers
{
    public class HotelController : Controller
    {
        private readonly HotelAppContext _context;
        private readonly HotelRepository _hotelRepository;

        public HotelController(HotelAppContext context,
            HotelRepository hotelRepository)
        {
            _context = context;
            _hotelRepository = hotelRepository;
        }

        public async Task<IActionResult> Index()
        {
            var data = await _hotelRepository.GetAllHotels();
            return View(data);
        }

        public async Task<IActionResult> SaveHotel(HotelModel model, int id = 0)
        {
            HotelModel hotel = new HotelModel();
            if (id != 0)
            {
                hotel = await _hotelRepository.GetHotelById(id);
            }
            return View(hotel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SaveHotel(int id, HotelModel model)
        {
            if (ModelState.IsValid)
            {
                await _hotelRepository.SaveHotel(model);
                return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this, "_HotelPartial", _context.Hotel.ToList()) });
            }
            return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "SaveHotel", model) });
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var hotel = await _context.Hotel.FindAsync(id);
            _context.Hotel.Remove(hotel);
            await _context.SaveChangesAsync();
            return Json(new { html = Helper.RenderRazorViewToString(this, "_HotelPartial", _context.Hotel.ToList()) });
        }
    }
}

Views/Hotel/Index.cshtml
@model IEnumerable<HotelApp.ViewModel.HotelModel>

@{
    ViewData["Title"] = "Index";
}

<h1 class="text-center">Hotel</h1>

<div id="view-all">
    @await Html.PartialAsync("_HotelPartial", Model)
</div>

Views/Hotel/SaveHotel.cshtml
@model HotelApp.ViewModel.HotelModel

@{
    ViewData["Title"] = "SaveHotel";
    Layout = null;
}

<div class="row">
    <div class="col-md-12">
        <form method="post" asp-action="SaveHotel" asp-route-id="@Model.Id" enctype="multipart/form-data" onsubmit="return jQueryAjaxPost(this);" autocomplete="off">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Floor" class="control-label"></label>
                <input asp-for="Floor" class="form-control" />
                <span asp-validation-for="Floor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Room" class="control-label"></label>
                <input asp-for="Room" class="form-control" />
                <span asp-validation-for="Room" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="SUBMIT" class="btn btn-primary btn-block" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Hotel/_HotelPartial.cshtml
@model IEnumerable<HotelApp.ViewModel.HotelModel>

<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th> @Html.DisplayNameFor(model => model.Id) </th>
            <th> @Html.DisplayNameFor(model => model.Floor) </th>
            <th> @Html.DisplayNameFor(model => model.Room) </th>
            <th>
                <a onclick="showInPopup('@Url.Action("SaveHotel", "Hotel", null, Context.Request.Scheme)', 'New Hotel')"
                   class="btn btn-success text-white">
                    Create New
                </a>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td> @Html.DisplayFor(modelItem => item.Id) </td>
                <td> @Html.DisplayFor(modelItem => item.Floor) </td>
                <td> @Html.DisplayFor(modelItem => item.Room) </td>
                <td>
                    <a onclick="showInPopup('@Url.Action("SaveHotel", "Hotel", new { id = item.Id }, Context.Request.Scheme)', 'Update Hotel')" class="btn btn-info text-white">
                        Edit
                    </a>
                    <form asp-action="Delete" asp-route-id="@item.Id" onsubmit="return jQueryAjaxDelete(this);" class="d-inline">
                        <input type="submit" value="DELETE" class="btn btn-danger" />
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>